#!/bin/bash
# backfill-handoff-index.sh — rebuild .startup/handoffs/INDEX.md from scratch.
#
# Intended for one-time migration on existing projects where handoffs predate
# the index-handoff.sh hook, or for manual recovery if INDEX.md drifts.
#
# Safe to re-run: overwrites INDEX.md with a fresh scan of the handoff dir.
# Sorted by handoff number (numbered files first, then unnumbered alphabetically).
#
# Usage:
#   bash backfill-handoff-index.sh                    # use git root's .startup/handoffs
#   bash backfill-handoff-index.sh /path/to/handoffs  # explicit dir

set -euo pipefail

if [ "$#" -ge 1 ]; then
  handoff_dir="$1"
else
  GIT_ROOT=$(git rev-parse --show-toplevel 2>/dev/null) || {
    echo "Not in a git repo and no dir argument supplied." >&2
    exit 1
  }
  handoff_dir="$GIT_ROOT/.startup/handoffs"
fi

if [ ! -d "$handoff_dir" ]; then
  echo "No handoffs dir at $handoff_dir" >&2
  exit 0
fi

index="$handoff_dir/INDEX.md"

extract_line() {
  local file="$1"
  local filename num direction date summary
  filename=$(basename "$file")

  if [[ "$filename" =~ ^([0-9]{3})- ]]; then
    num="${BASH_REMATCH[1]}"
  else
    num="---"
  fi

  direction="other"
  case "$filename" in
    *business-to-tech*)   direction="business-to-tech" ;;
    *tech-to-business*)   direction="tech-to-business" ;;
    *business-to-growth*) direction="business-to-growth" ;;
    *growth-to-business*) direction="growth-to-business" ;;
    *business-qa*)        direction="business-qa" ;;
    *business-review*)    direction="business-review" ;;
  esac

  date=$(awk '/^date:/ {gsub(/"/,"",$2); print $2; exit}' "$file" 2>/dev/null | head -c 10)
  if ! [[ "$date" =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}$ ]]; then
    date=$(date -r "$file" +%Y-%m-%d 2>/dev/null || echo "----------")
  fi

  summary=$(awk '
    /^## Summary/ {found=1; next}
    found && /^##/ {exit}
    found && NF>0 {print; exit}
  ' "$file" 2>/dev/null | tr '\n' ' ' | sed 's/^[[:space:]]*//; s/[[:space:]]*$//')

  if [ -z "$summary" ]; then
    summary=$(awk '
      BEGIN {fm=0}
      /^---$/ {fm = !fm; next}
      fm {next}
      /^#/ {next}
      NF>0 {print; exit}
    ' "$file" 2>/dev/null)
  fi

  summary=$(printf '%s' "$summary" | tr '|' '/' | tr -d '\r' | cut -c1-120)
  echo "${num} | ${direction} | ${date} | ${filename} | ${summary}"
}

cat > "$index" <<'EOF'
# Handoff Index

Auto-generated by saas-startup-team plugin. Regenerate with `backfill-handoff-index.sh`.

Format: `NNN | direction | date | filename | summary`

EOF

shopt -s nullglob
numbered_tmp=$(mktemp)
unnumbered_tmp=$(mktemp)
count=0

for f in "$handoff_dir"/*.md; do
  filename=$(basename "$f")
  [ "$filename" = "INDEX.md" ] && continue
  line=$(extract_line "$f")
  if [[ "$line" =~ ^[0-9]{3} ]]; then
    echo "$line" >> "$numbered_tmp"
  else
    echo "$line" >> "$unnumbered_tmp"
  fi
  count=$((count + 1))
done

sort -t'|' -k1,1 "$numbered_tmp" >> "$index"
sort -t'|' -k4,4 "$unnumbered_tmp" >> "$index"
rm -f "$numbered_tmp" "$unnumbered_tmp"

echo "Wrote $index — indexed $count handoff(s)."
