#!/bin/bash
# index-handoff.sh — PostToolUse hook for Write events.
# Maintains .startup/handoffs/INDEX.md so handoffs are discoverable without
# globbing the full directory (which grows past 500 files on long-running projects).
#
# Appends or upserts one line per handoff:
#   NNN | direction | date | filename | summary
#
# Exit 0 always — failure must NOT block the original Write. The index is a
# convenience, not a source of truth.

set -uo pipefail

input=$(cat || true)
file_path=$(echo "$input" | jq -r '.tool_input.file_path // empty' 2>/dev/null) || exit 0
[ -z "$file_path" ] && exit 0

case "$file_path" in
  */.startup/handoffs/*.md) ;;
  *) exit 0 ;;
esac

filename=$(basename "$file_path")
[ "$filename" = "INDEX.md" ] && exit 0
[ -f "$file_path" ] || exit 0

handoff_dir=$(dirname "$file_path")
index="$handoff_dir/INDEX.md"

# --- Extract fields ---
if [[ "$filename" =~ ^([0-9]{3})- ]]; then
  num="${BASH_REMATCH[1]}"
else
  num="---"
fi

direction="other"
case "$filename" in
  *business-to-tech*)   direction="business-to-tech" ;;
  *tech-to-business*)   direction="tech-to-business" ;;
  *business-to-growth*) direction="business-to-growth" ;;
  *growth-to-business*) direction="growth-to-business" ;;
  *business-qa*)        direction="business-qa" ;;
  *business-review*)    direction="business-review" ;;
esac

date=$(awk '/^date:/ {gsub(/"/,"",$2); print $2; exit}' "$file_path" 2>/dev/null | head -c 10)
if ! [[ "$date" =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}$ ]]; then
  date=$(date -r "$file_path" +%Y-%m-%d 2>/dev/null || echo "----------")
fi

summary=$(awk '
  /^## Summary/ {found=1; next}
  found && /^##/ {exit}
  found && NF>0 {print; exit}
' "$file_path" 2>/dev/null | tr '\n' ' ' | sed 's/^[[:space:]]*//; s/[[:space:]]*$//')

if [ -z "$summary" ]; then
  summary=$(awk '
    BEGIN {fm=0}
    /^---$/ {fm = !fm; next}
    fm {next}
    /^#/ {next}
    NF>0 {print; exit}
  ' "$file_path" 2>/dev/null)
fi

summary=$(printf '%s' "$summary" | tr '|' '/' | tr -d '\r' | cut -c1-120)

line="${num} | ${direction} | ${date} | ${filename} | ${summary}"

if [ ! -f "$index" ]; then
  cat > "$index" <<'EOF'
# Handoff Index

Auto-generated by saas-startup-team plugin. Regenerate with `backfill-handoff-index.sh`.

Format: `NNN | direction | date | filename | summary`

EOF
fi

tmp=$(mktemp)
grep -vF "| ${filename} |" "$index" > "$tmp" 2>/dev/null || true
mv "$tmp" "$index"
echo "$line" >> "$index"

exit 0
